### Users create (signup)
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "phil",
  "email": "phil@example.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}

### Dog create
POST http://localhost:3000/dogs.json 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MzUxMDE1MDB9.gm6gBMzLMmSh650Fod6jIjwmG1yvDRoDMFUMboQLwcw

{
  "name": "Gizmo",
  "age": 1,
  "breed": "Bichon Frise"
}